highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: :title.html
paginate: 5
plugins: [jekyll-paginate]
port: 4000
safe: true
url: http://jideguru.github.io/
author: JideGuru

# edit this section with your information
# jekyller.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /
title: JideGuru's Resume
name: Olusegun Festus Babajide
email: guruliciousjide@gmail.com
email_full: mailto:guruliciousjide@gmail.com
website: http://jideguru.github.io/
website_full: https://jideguru.github.io/
github: JideGuru
twitter: iamjideguru
tel: +229 94 68 44 68
tel_full: tel:+22994684468
google_maps: 'https://www.google.com/maps?q=6.468017,2.641644'
address:
  street: 1818 Agbokou Jibite
  postcode: 00229
  city: Porto Novo
  country: Benin Republic
google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
